language: java

jdk:
        - oraclejdk8
        - openjdk7

env:
        - SONARHOME=/tmp/sonarqube-4.5.4
        - SONARHOME=/tmp/sonarqube-5.0.1
        - SONARHOME=/tmp/sonarqube-5.1.1
  
before_install:
        - travis_retry sudo apt-add-repository -y ppa:boost-latest/ppa
        - travis_retry sudo apt-get -qq update
        - travis_retry sudo apt-get -qq install boost1.55
        
install:
        - cd /tmp      
        - travis_retry wget -q http://dist.sonar.codehaus.org/sonarqube-4.5.4.zip
        - unzip -qq sonarqube-4.5.4.zip        
        - travis_retry wget -q http://dist.sonar.codehaus.org/sonarqube-5.0.1.zip
        - unzip -qq sonarqube-5.0.1.zip
        - travis_retry wget -q http://dist.sonar.codehaus.org/sonarqube-5.1.1.zip
        - unzip -qq sonarqube-5.1.1.zip        
        - travis_retry wget -q http://repo1.maven.org/maven2/org/codehaus/sonar/runner/sonar-runner-dist/2.4/sonar-runner-dist-2.4.zip
        - unzip -qq sonar-runner-dist-2.4.zip
        - cd -

before_script:
        - travis_retry sudo pip install -q requests
        - travis_retry sudo pip install -q behave
        - travis_retry sudo pip install -q colorama

script:
        - mvn install -DskipTests=true
        - mvn test
        - RAILS_ENV=production PATH=$PATH:/tmp/sonar-runner-2.4/bin behave
